// Generated by 'unplugin-auto-import'
// We suggest you to commit this file into source control
declare global {
  const ElAside: typeof import('element-plus/es')['ElAside']
  const ElContainer: typeof import('element-plus/es')['ElContainer']
  const ElFooter: typeof import('element-plus/es')['ElFooter']
  const ElForm: typeof import('element-plus/es')['ElForm']
  const ElFormItem: typeof import('element-plus/es')['ElFormItem']
  const ElHeader: typeof import('element-plus/es')['ElHeader']
  const ElInput: typeof import('element-plus/es')['ElInput']
  const ElMain: typeof import('element-plus/es')['ElMain']
}
export {}
