// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Bottom: typeof import('./src/components/layout/bottom.vue')['default']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    Left_menu: typeof import('./src/components/layout/left_menu.vue')['default']
    Toolbar: typeof import('./src/components/layout/toolbar.vue')['default']
  }
}

export { }
